### ISSUE TITLE
HTTP Proxy did not start on [IP]

### ISSUE THREAD

**Issue by tweenietomatoes** [oracle/nosql-examples#21]
I am getting, HTTP Proxy did not start on X.X.X.X

Here is the log file:
Error: Unable to access jarfile /opt/oracle/nosql/proxy/lib/httpproxy.jar

Oracle Linux 8, running on Oracle Cloud.

Single node installation on same machine.

**Comment by connelly38** [comment]
Are you using kv-ce or kv-ee?

**Comment by tweenietomatoes** [comment]
kv-ce

**Comment by tweenietomatoes** [comment]
according to the documentation kv-ce also includes http proxy :(

**Comment by connelly38** [comment]
OK. The issue is that the latest version of the cluster_setup script assumes that the httpproxy jar file is contained in the kv-*.tar.gz, which works fine for kv-ee. But kv-ce does not contain httpproxy, so the workaround is to use an older version of the script, which allows you to set up httpproxy from a separately downloaded tar.gz file. But- first you'll need to modify the script to change the max java version, as we did earlier today with the latest version.

Direct link to download the previous version that uses separate httpproxy download: https://raw.githubusercontent.com/oracle/nosql-examples/a4e870618effe0d7e3d222393c377262eebd6b25/cluster_setup/cluster_setup.sh

**Comment by connelly38** [comment]
You'll need to modify line 882 of that script to enable java 14. 
change:
version -gt 13 
to
version -gt 14

**Comment by tweenietomatoes** [comment]
is that version of script downloading proxy online?

**Comment by connelly38** [comment]
Working on verifying the httpproxy issue. The proxy is no longer available on Oracle's download site, so working on finding another way.

**Comment by tweenietomatoes** [comment]
well i didn't understand why cluster_setup and httpproxy is not included in tar.gz
it's definitely not user friendly and docs are confusing that nobody knows there is a nosql database of oracle... :(

**Comment by connelly38** [comment]
It looks as though httpproxy isn't compatible with the kv-ce version anyway. I'll be modifying the setup script to not attempt proxy install with CE version.
If I'm not mistaken, the setup should have actually worked for the base nosql server install, and should be up and running and reachable by the java client code.

**Comment by tweenietomatoes** [comment]
it's ok but i have a 1 grpc server with java and 1 rest api with nodejs.
i won't be able to communicate with node client.

**Comment by connelly38** [comment]
You can verify this by running /opt/oracle/nosql/kvstore/scripts/kvstore_ping.sh

**Comment by connelly38** [comment]
You should be able to use the thrift-based node.js driver located at https://www.npmjs.com/package/nosqldb-oraclejs. For more info you can contact michael.brey@oracle.com.
